version: "3.9"
services:
  frontend:
    container_name: frontend
    image: frontend
    build: ./frontend
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
  mongo:
    container_name: mongo
    image: mongo
    build: ./mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - backend
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    build: ./mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    ports:
      - "8081:8081"
volumes:
  mongodata:
networks:
  frontend:
  backend:
    internal: true
