version: "3.9"
services:
  frontend:
    container_name: frontend
    image: frontend
    build: ./frontend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/pizzeria
      - PORT=3000
      - SECRET=aslbljwerljwer
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
  mongo:
    container_name: mongo
    image: mongo
    build: ./mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - backend
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    build: ./mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    links:
      - mongo
    networks:
      - backend
volumes:
  mongodata:
networks:
  frontend:
  backend:
    internal: true
